name: Bug report
description: Report a reproducible bug in Elbert
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill out the details below.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-line description of the bug
      placeholder: "Launcher does not open after hotkey change"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps so we can reproduce it
      placeholder: |
        1. Open Settings
        2. Change hotkey to ...
        3. Press shortcut
        4. Observe behavior
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: "The launcher should open"
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: "Nothing happens and no error is shown"
    validations:
      required: true
  - type: input
    id: macos
    attributes:
      label: macOS version
      placeholder: "macOS 15.4"
    validations:
      required: true
  - type: input
    id: xcode
    attributes:
      label: Xcode version (if relevant)
      placeholder: "Xcode 16.2"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste logs or attach screenshots if available
    validations:
      required: false
